In [1]:
import pandas as pd
import numpy as np

In [2]:
df_yes = pd.read_csv('table_yes_service.csv')
df_no = pd.read_csv('최종 데이터(no service).csv')

In [3]:
df_yes

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,age_20s_sales_amount,age_30s_sales_amount,age_40s_sales_amount,age_50s_sales_amount,age_60_and_above_sales_amount,male_sales_amount,female_sales_amount,similar_business_count,open_store_count,closed_store_count
0,20211,송파구 위례동,일식음식점,0.0,0.0,0.00,7,3,10,1.280793e+08,...,22736885.0,3.003526e+07,2.542466e+07,2.089114e+07,1.033250e+07,6.301554e+07,4.826760e+07,10.0,0.0,0.0
1,20211,송파구 위례동,일반의원,0.0,0.0,0.00,9,0,9,8.908356e+07,...,3942037.0,3.481527e+07,3.467658e+07,6.699324e+06,8.876192e+06,3.909593e+07,4.998763e+07,9.0,0.0,0.0
2,20211,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,2.637117e+07,...,5657408.0,7.098145e+06,7.622582e+06,3.670382e+06,9.778620e+05,5.127652e+06,2.008478e+07,6.0,0.0,0.0
3,20212,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,3.986154e+07,...,6269568.0,8.331579e+06,1.340179e+07,6.333551e+06,1.714392e+06,1.767246e+07,2.006241e+07,10.0,0.0,0.0
4,20212,송파구 위례동,제과점,0.0,13.0,-0.13,8,6,14,4.554559e+08,...,35998568.0,1.288304e+08,1.318839e+08,6.770419e+07,5.399467e+07,1.710404e+08,2.494101e+08,14.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497328,20234,송파구 가락1동,한의원,0.0,0.0,0.00,5,0,5,2.144828e+07,...,0.0,1.877619e+06,3.936613e+06,5.980280e+06,9.653772e+06,9.893902e+06,1.155438e+07,5.0,0.0,0.0
497329,20234,송파구 가락1동,자동차수리,0.0,0.0,0.00,7,0,7,1.938506e+07,...,0.0,0.000000e+00,0.000000e+00,1.199076e+06,1.031932e+07,4.868975e+06,6.649421e+06,7.0,0.0,0.0
497330,20234,송파구 가락1동,미곡판매,0.0,0.0,0.00,11,0,11,2.068183e+10,...,0.0,2.066022e+09,1.516018e+09,4.355617e+09,9.875087e+09,6.184036e+09,1.162871e+10,11.0,0.0,0.0
497331,20234,송파구 가락1동,의약품,0.0,6.0,-0.06,17,0,17,3.045047e+08,...,12779211.0,2.769253e+07,5.644236e+07,1.006256e+08,1.014575e+08,1.796149e+08,1.193823e+08,17.0,0.0,1.0
497332,20234,송파구 가락1동,분식전문점,6.0,28.0,-0.22,32,3,35,4.286859e+08,...,30646036.0,6.439636e+07,5.846979e+07,5.457277e+07,1.559616e+07,1.546346e+08,6.904647e+07,35.0,2.0,9.0

In [5]:
df_no

,quarter,dong,pop_total,pop_male,pop_female,pop_floating,visitor_facility_count,avg_monthly_income,total_expenditure,monthly_rent_per_pyeong
0,20211,중구 명동,8749,3737,5012,8402492,542,3733600,46546968000,180600.0
1,20212,중구 명동,8644,3733,4911,10284398,542,3733600,55297008000,171684.0
2,20213,중구 명동,8580,3746,4834,9011375,542,3733600,55509810000,179329.0
3,20214,중구 명동,8625,3772,4853,11323327,542,3733600,63917672000,189983.0
4,20221,중구 명동,8597,3749,4848,9344018,542,3733600,62275801000,197310.0
...,...,...,...,...,...,...,...,...,...,...
5973,20232,종로구 종로5.6가동,16282,8588,7694,5466638,212,2531450,9406493000,293452.0
5974,20233,종로구 종로5.6가동,16272,8585,7687,4934033,212,2531450,8717278000,293318.0
5975,20234,종로구 종로5.6가동,16169,8514,7655,5069880,212,2531450,9876132000,297493.0
5976,20241,종로구 종로5.6가동,16061,8441,7620,4692154,212,2531450,3164045000,296837.0
5977,20242,종로구 종로5.6가동,16015,8414,7601,4991461,212,2531450,10086352000,277462.0

In [6]:
# 서비스 대분류 생성 함수 수정 및 적용
def categorize_service(service_name):
    if '학원' in service_name or '독서실' in service_name or '컴퓨터학원' in service_name:
        return '교육업'
    elif ('슈퍼마켓' in service_name or '편의점' in service_name or '판매' in service_name or
          '의약품' in service_name or '서적' in service_name or '화장품' in service_name or 
          '가방' in service_name or '시계' in service_name or '핸드폰' in service_name or
          '중고차판매' in service_name or '가전제품' in service_name or '가구' in service_name or
          '청과상' in service_name or '육류' in service_name or '수산물' in service_name):
        return '소매업'
    elif ('음식점' in service_name or '커피' in service_name or '음료' in service_name or 
          '제과점' in service_name or '패스트푸드' in service_name or '분식' in service_name or
          '치킨' in service_name or '호프' in service_name or '간이주점' in service_name):
        return '음식업'
    elif ('의원' in service_name or '병원' in service_name or '의료' in service_name or
          '동물병원' in service_name or '한의원' in service_name):
        return '의료업'
    elif ('부동산' in service_name or '법무' in service_name or '여행사' in service_name or
          '통번역' in service_name or '청소' in service_name or '세무' in service_name or
          '변호사' in service_name or '회계사' in service_name or '변리사' in service_name):
        return '서비스업'
    elif ('PC방' in service_name or '당구장' in service_name or '골프' in service_name or 
          '스포츠' in service_name or '노래방' in service_name or '볼링장' in service_name or
          'DVD방' in service_name or '비디오' in service_name or '오락장' in service_name):
        return '레저/여가업'
    else:
        return '기타'

# 새로운 열 추가
df_yes['major'] = df_yes['service'].apply(categorize_service)

In [7]:
df_yes

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,age_30s_sales_amount,age_40s_sales_amount,age_50s_sales_amount,age_60_and_above_sales_amount,male_sales_amount,female_sales_amount,similar_business_count,open_store_count,closed_store_count,major
0,20211,송파구 위례동,일식음식점,0.0,0.0,0.00,7,3,10,1.280793e+08,...,3.003526e+07,2.542466e+07,2.089114e+07,1.033250e+07,6.301554e+07,4.826760e+07,10.0,0.0,0.0,음식업
1,20211,송파구 위례동,일반의원,0.0,0.0,0.00,9,0,9,8.908356e+07,...,3.481527e+07,3.467658e+07,6.699324e+06,8.876192e+06,3.909593e+07,4.998763e+07,9.0,0.0,0.0,의료업
2,20211,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,2.637117e+07,...,7.098145e+06,7.622582e+06,3.670382e+06,9.778620e+05,5.127652e+06,2.008478e+07,6.0,0.0,0.0,기타
3,20212,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,3.986154e+07,...,8.331579e+06,1.340179e+07,6.333551e+06,1.714392e+06,1.767246e+07,2.006241e+07,10.0,0.0,0.0,음식업
4,20212,송파구 위례동,제과점,0.0,13.0,-0.13,8,6,14,4.554559e+08,...,1.288304e+08,1.318839e+08,6.770419e+07,5.399467e+07,1.710404e+08,2.494101e+08,14.0,0.0,1.0,음식업
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497328,20234,송파구 가락1동,한의원,0.0,0.0,0.00,5,0,5,2.144828e+07,...,1.877619e+06,3.936613e+06,5.980280e+06,9.653772e+06,9.893902e+06,1.155438e+07,5.0,0.0,0.0,의료업
497329,20234,송파구 가락1동,자동차수리,0.0,0.0,0.00,7,0,7,1.938506e+07,...,0.000000e+00,0.000000e+00,1.199076e+06,1.031932e+07,4.868975e+06,6.649421e+06,7.0,0.0,0.0,기타
497330,20234,송파구 가락1동,미곡판매,0.0,0.0,0.00,11,0,11,2.068183e+10,...,2.066022e+09,1.516018e+09,4.355617e+09,9.875087e+09,6.184036e+09,1.162871e+10,11.0,0.0,0.0,소매업
497331,20234,송파구 가락1동,의약품,0.0,6.0,-0.06,17,0,17,3.045047e+08,...,2.769253e+07,5.644236e+07,1.006256e+08,1.014575e+08,1.796149e+08,1.193823e+08,17.0,0.0,1.0,소매업
497332,20234,송파구 가락1동,분식전문점,6.0,28.0,-0.22,32,3,35,4.286859e+08,...,6.439636e+07,5.846979e+07,5.457277e+07,1.559616e+07,1.546346e+08,6.904647e+07,35.0,2.0,9.0,음식업

In [8]:
df_yes[df_yes['major']=='기타'].head()

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,age_30s_sales_amount,age_40s_sales_amount,age_50s_sales_amount,age_60_and_above_sales_amount,male_sales_amount,female_sales_amount,similar_business_count,open_store_count,closed_store_count,major
2,20211,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,26371172.0,...,7098145.0,7622582.0,3670382.0,977862.0,5127652.0,20084782.0,6.0,0.0,0.0,기타
5,20212,송파구 위례동,미용실,0.0,0.0,0.00,24,4,28,208065233.0,...,71235910.0,69750466.0,24720063.0,20819173.0,85082423.0,122982810.0,28.0,0.0,0.0,기타
7,20212,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,30522280.0,...,3592011.0,10510547.0,6154141.0,1910307.0,12771657.0,16733195.0,6.0,0.0,0.0,기타
10,20213,송파구 위례동,미용실,0.0,4.0,-0.04,23,4,27,246912941.0,...,74137270.0,81804411.0,37767889.0,16808385.0,109197245.0,137715696.0,27.0,0.0,1.0,기타
11,20213,송파구 위례동,네일숍,0.0,0.0,0.00,8,0,8,83184896.0,...,21190445.0,23614996.0,21307977.0,4338474.0,31358143.0,50160245.0,8.0,0.0,0.0,기타

In [9]:
gentrification_categories = ['음식업', '소매업']
df_gentrification = df_yes[df_yes['major'].isin(gentrification_categories)]

In [10]:
df_gentrification = df_yes.copy()

In [11]:
# '음식업'과 '소매업'만을 사용하여 LQ 지수를 계산하고 필요한 파생 변수를 생성
# 먼저 특정 분기 서울시 전체 점포 수와 행정동별 점포수를 계산

df_gentrification['seoul_total_store_cnt'] = df_gentrification.groupby(['quarter'])['store_count'].transform('sum')
df_gentrification['dong_total_store_cnt'] = df_gentrification.groupby(['quarter', 'dong'])['store_count'].transform('sum')
df_gentrification.head(50)

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,age_50s_sales_amount,age_60_and_above_sales_amount,male_sales_amount,female_sales_amount,similar_business_count,open_store_count,closed_store_count,major,seoul_total_store_cnt,dong_total_store_cnt
0,20211,송파구 위례동,일식음식점,0.0,0.0,0.00,7,3,10,1.280793e+08,...,20891141.0,10332502.0,63015544.0,48267598.0,10.0,0.0,0.0,음식업,558929,681.0
1,20211,송파구 위례동,일반의원,0.0,0.0,0.00,9,0,9,8.908356e+07,...,6699324.0,8876192.0,39095929.0,49987626.0,9.0,0.0,0.0,의료업,558929,681.0
2,20211,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,2.637117e+07,...,3670382.0,977862.0,5127652.0,20084782.0,6.0,0.0,0.0,기타,558929,681.0
3,20212,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,3.986154e+07,...,6333551.0,1714392.0,17672455.0,20062408.0,10.0,0.0,0.0,음식업,569022,712.0
4,20212,송파구 위례동,제과점,0.0,13.0,-0.13,8,6,14,4.554559e+08,...,67704189.0,53994666.0,171040438.0,249410127.0,14.0,0.0,1.0,음식업,569022,712.0
5,20212,송파구 위례동,미용실,0.0,0.0,0.00,24,4,28,2.080652e+08,...,24720063.0,20819173.0,85082423.0,122982810.0,28.0,0.0,0.0,기타,569022,712.0
6,20212,송파구 위례동,편의점,0.0,100.0,-1.00,1,20,21,1.884032e+08,...,28123856.0,14407496.0,116387742.0,72015505.0,21.0,0.0,1.0,소매업,569022,712.0
7,20212,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,3.052228e+07,...,6154141.0,1910307.0,12771657.0,16733195.0,6.0,0.0,0.0,기타,569022,712.0
8,20213,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,3.351970e+07,...,6298782.0,1200581.0,16250239.0,15130463.0,10.0,0.0,0.0,음식업,578377,724.0
9,20213,송파구 위례동,일반의원,0.0,0.0,0.00,10,0,10,1.269772e+08,...,13167327.0,14234025.0,56846586.0,70130600.0,10.0,0.0,0.0,의료업,578377,724.0
10,20213,송파구 위례동,미용실,0.0,4.0,-0.04,23,4,27,2.469129e+08,...,37767889.0,16808385.0,109197245.0,137715696.0,27.0,0.0,1.0,기타,578377,724.0
11,20213,송파구 위례동,네일숍,0.0,0.0,0.00,8,0,8,8.318490e+07,...,21307977.0,4338474.0,31358143.0,50160245.0,8.0,0.0,0.0,기타,578377,724.0
12,20213,송파구 위례동,청과상,0.0,22.0,-0.22,9,0,9,2.533987e+08,...,61802135.0,45087644.0,102085593.0,147635721.0,9.0,0.0,2.0,소매업,578377,724.0
13,20213,송파구 위례동,안경,0.0,0.0,0.00,2,4,6,3.744531e+07,...,6720113.0,2396609.0,18700895.0,17783514.0,6.0,0.0,0.0,기타,578377,724.0
14,20213,송파구 위례동,의약품,0.0,0.0,0.00,11,1,12,1.044678e+08,...,13591439.0,8217811.0,52200379.0,52267439.0,12.0,0.0,0.0,소매업,578377,724.0
15,20214,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,2.625445e+07,...,3420779.0,1716519.0,11342974.0,12811264.0,10.0,0.0,0.0,음식업,595141,805.0
16,20214,송파구 위례동,일반의원,0.0,0.0,0.00,10,0,10,2.494455e+08,...,20366034.0,13305883.0,126134765.0,123310769.0,10.0,0.0,0.0,의료업,595141,805.0
17,20214,송파구 위례동,세탁소,0.0,0.0,0.00,4,1,5,1.845509e+07,...,4511761.0,1499808.0,5572454.0,10706085.0,5.0,0.0,0.0,기타,595141,805.0
18,20214,송파구 위례동,청과상,0.0,0.0,0.00,9,0,9,3.079174e+08,...,67199719.0,63492521.0,116507182.0,173484748.0,9.0,0.0,0.0,소매업,595141,805.0
19,20214,송파구 위례동,의약품,0.0,0.0,0.00,11,1,12,1.627229e+08,...,12597067.0,6287185.0,79643244.0,83079618.0,12.0,0.0,0.0,소매업,595141,805.0
20,20221,송파구 위례동,일식음식점,0.0,11.0,-0.11,9,4,13,1.718366e+08,...,23497347.0,12881022.0,89551802.0,57410396.0,13.0,0.0,1.0,음식업,585121,805.0
21,20221,송파구 위례동,제과점,0.0,0.0,0.00,12,6,18,4.929128e+08,...,81608676.0,56354650.0,188232414.0,278806041.0,18.0,0.0,0.0,음식업,585121,805.0
22,20221,송파구 위례동,일반의원,0.0,0.0,0.00,10,0,10,2.042830e+08,...,21047130.0,11940493.0,96628954.0,107654011.0,10.0,0.0,0.0,의료업,585121,805.0
23,20221,송파구 위례동,미용실,0.0,0.0,0.00,25,4,29,2.640705e+08,...,45668403.0,18940254.0,118838855.0,145231635.0,29.0,0.0,0.0,기타,585121,805.0
24,20221,송파구 위례동,세탁소,0.0,0.0,0.00,4,1,5,1.959504e+07,...,1859517.0,1420549.0,6712550.0,10724229.0,5.0,0.0,0.0,기타,585121,805.0
25,20221,송파구 위례동,슈퍼마켓,0.0,0.0,0.00,10,2,12,2.680255e+07,...,6594701.0,2457598.0,10051324.0,15931438.0,12.0,0.0,0.0,소매업,585121,805.0
26,20221,송파구 위례동,안경,0.0,100.0,-1.00,1,4,5,3.593782e+07,...,3442486.0,5826990.0,15501180.0,18690059.0,5.0,0.0,1.0,기타,585121,805.0
27,20221,송파구 위례동,의약품,0.0,0.0,0.00,11,1,12,2.166450e+08,...,24495476.0,12948544.0,98111713.0,118533257.0,12.0,0.0,0.0,소매업,585121,805.0
28,20222,송파구 위례동,일식음식점,0.0,0.0,0.00,9,4,13,1.944896e+08,...,25728666.0,15294497.0,99536787.0,69512106.0,13.0,0.0,0.0,음식업,585966,833.0
29,20222,송파구 위례동,일반의원,0.0,0.0,0.00,10,0,10,2.064706e+08,...,17947428.0,14358494.0,98155657.0,108314950.0,10.0,0.0,0.0,의료업,585966,833.0
30,20222,송파구 위례동,미용실,0.0,0.0,0.00,25,4,29,2.822907e+08,...,42149992.0,24286878.0,120334541.0,160985105.0,29.0,0.0,0.0,기타,585966,833.0
31,20222,송파구 위례동,네일숍,0.0,0.0,0.00,9,0,9,1.138050e+08,...,15493200.0,8488333.0,25372621.0,88432397.0,9.0,0.0,0.0,기타,585966,833.0
32,20222,송파구 위례동,세탁소,0.0,0.0,0.00,4,1,5,3.205685e+07,...,5852906.0,3749517.0,10913229.0,17747716.0,5.0,0.0,0.0,기타,585966,833.0
33,20222,송파구 위례동,의약품,0.0,22.0,-0.22,9,1,10,1.823513e+08,...,20646595.0,14034770.0,87060066.0,95291189.0,10.0,0.0,2.0,소매업,585966,833.0
34,20223,송파구 위례동,일식음식점,0.0,29.0,-0.29,7,4,11,1.853529e+08,...,21911241.0,14845552.0,102832323.0,64356427.0,11.0,0.0,2.0,음식업,580620,854.0
35,20223,송파구 위례동,양식음식점,0.0,0.0,0.00,8,4,12,1.066488e+07,...,1596316.0,1019598.0,4997322.0,5176966.0,12.0,0.0,0.0,음식업,580620,854.0
36,20223,송파구 위례동,일반의원,0.0,0.0,0.00,10,0,10,3.456821e+08,...,48904364.0,21819385.0,155242455.0,190439651.0,10.0,0.0,0.0,의료업,580620,854.0
37,20223,송파구 위례동,미용실,0.0,0.0,0.00,25,4,29,2.757409e+08,...,39024795.0,16105208.0,130697495.0,144636885.0,29.0,0.0,0.0,기타,580620,854.0
38,20223,송파구 위례동,네일숍,0.0,0.0,0.00,9,0,9,7.936221e+07,...,13343365.0,9398439.0,23945021.0,54316043.0,9.0,0.0,0.0,기타,580620,854.0
39,20223,송파구 위례동,의약품,0.0,13.0,-0.13,8,1,9,2.471319e+08,...,29061453.0,22980774.0,121013960.0,126117948.0,9.0,0.0,1.0,소매업,580620,854.0
40,20211,송파구 위례동,커피-음료,11.0,0.0,0.11,19,8,27,1.135476e+09,...,108021934.0,51963876.0,461427469.0,620529117.0,27.0,2.0,0.0,음식업,558929,681.0
41,20213,송파구 위례동,한식음식점,4.0,2.0,0.02,45,21,66,3.974473e+08,...,80956734.0,47832167.0,179410549.0,195045457.0,66.0,2.0,1.0,음식업,578377,724.0
42,20214,송파구 위례동,일식음식점,20.0,0.0,0.20,10,4,14,1.614926e+08,...,10332439.0,14268035.0,85004988.0,52226485.0,14.0,2.0,0.0,음식업,595141,805.0
43,20221,송파구 위례동,분식전문점,11.0,11.0,0.00,18,6,24,6.027598e+07,...,6686022.0,1087615.0,26321842.0,33233275.0,24.0,2.0,2.0,음식업,585121,805.0
44,20221,송파구 위례동,편의점,0.0,0.0,0.00,0,25,25,3.210630e+08,...,48618338.0,34648589.0,197230211.0,123832822.0,25.0,2.0,2.0,소매업,585121,805.0
45,20222,송파구 위례동,한식음식점,4.0,2.0,0.02,53,20,73,4.376675e+08,...,88832596.0,50123394.0,233634382.0,196764716.0,73.0,2.0,1.0,음식업,585966,833.0
46,20223,송파구 위례동,분식전문점,10.0,5.0,0.05,20,6,26,7.812450e+07,...,9102016.0,925165.0,36650843.0,40200582.0,26.0,2.0,1.0,음식업,580620,854.0
47,20211,송파구 위례동,편의점,300.0,100.0,2.00,1,21,22,1.874327e+08,...,36621951.0,12648093.0,119734235.0,67698453.0,22.0,3.0,1.0,소매업,558929,681.0
48,20212,송파구 위례동,분식전문점,17.0,11.0,0.06,18,8,26,3.876205e+07,...,3922049.0,1211918.0,15824254.0,21573555.0,26.0,3.0,2.0,음식업,569022,712.0
49,20213,송파구 위례동,제과점,27.0,0.0,0.27,11,6,17,4.938077e+08,...,69190881.0,55413196.0,206648066.0,269087328.0,17.0,3.0,0.0,음식업,578377,724.0

In [12]:
# 음식업 데이터 필터링 및 외식업 점포 비율 LQ 지수 계산
food_service_df = df_gentrification[df_gentrification['major'] == '음식업'].copy()

food_service_df['food_store_cnt'] = food_service_df.groupby(['quarter', 'dong'])['store_count'].transform('sum')
food_service_df['food_store_total_cnt'] = food_service_df.groupby('quarter')['store_count'].transform('sum')
food_service_df['food_service_lq'] = (food_service_df['food_store_cnt'] / food_service_df['dong_total_store_cnt']) / (
food_service_df['food_store_total_cnt'] / food_service_df['seoul_total_store_cnt'])

food_service_df

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,female_sales_amount,similar_business_count,open_store_count,closed_store_count,major,seoul_total_store_cnt,dong_total_store_cnt,food_store_cnt,food_store_total_cnt,food_service_lq
0,20211,송파구 위례동,일식음식점,0.0,0.0,0.00,7,3,10,128079310.0,...,48267598.0,10.0,0.0,0.0,음식업,558929,681.0,115.0,119043,0.792873
3,20212,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,39861542.0,...,20062408.0,10.0,0.0,0.0,음식업,569022,712.0,124.0,120409,0.823023
4,20212,송파구 위례동,제과점,0.0,13.0,-0.13,8,6,14,455455883.0,...,249410127.0,14.0,0.0,1.0,음식업,569022,712.0,124.0,120409,0.823023
8,20213,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,33519703.0,...,15130463.0,10.0,0.0,0.0,음식업,578377,724.0,125.0,121145,0.824284
15,20214,송파구 위례동,양식음식점,0.0,0.0,0.00,6,4,10,26254447.0,...,12811264.0,10.0,0.0,0.0,음식업,595141,805.0,135.0,122150,0.817079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497321,20233,송파구 가락1동,분식전문점,3.0,5.0,-0.03,40,3,43,317217806.0,...,33928134.0,43.0,1.0,2.0,음식업,585288,3375.0,223.0,127227,0.303963
497322,20241,송파구 가락1동,양식음식점,20.0,0.0,0.20,5,0,5,150239987.0,...,58310261.0,5.0,1.0,0.0,음식업,577728,3311.0,210.0,127884,0.286528
497324,20242,송파구 가락1동,분식전문점,4.0,0.0,0.04,27,2,29,271493791.0,...,23058927.0,29.0,1.0,0.0,음식업,575909,3295.0,207.0,128127,0.282376
497325,20234,송파구 가락1동,호프-간이주점,0.0,0.0,0.00,3,2,5,858000000.0,...,156367048.0,5.0,0.0,0.0,음식업,584072,3346.0,210.0,128131,0.286092
497332,20234,송파구 가락1동,분식전문점,6.0,28.0,-0.22,32,3,35,428685942.0,...,69046471.0,35.0,2.0,9.0,음식업,584072,3346.0,210.0,128131,0.286092

In [13]:
# 소매업 데이터 필터링 및 소매업 점포 비율 LQ 지수 계산
retail_df = df_gentrification[df_gentrification['major'] == '소매업'].copy()

retail_df['food_store_cnt'] = retail_df.groupby(['quarter', 'dong'])['store_count'].transform('sum')
retail_df['food_store_total_cnt'] = retail_df.groupby('quarter')['store_count'].transform('sum')
retail_df['retail_lq'] = (retail_df['food_store_cnt'] / retail_df['dong_total_store_cnt']) / (
retail_df['food_store_total_cnt'] / retail_df['seoul_total_store_cnt'])

retail_df

,quarter,dong,service,opening_rate,closure_rate,store_net_growth_rate,store_count,franchise_count,store_total_count,current_month_sales_amount,...,female_sales_amount,similar_business_count,open_store_count,closed_store_count,major,seoul_total_store_cnt,dong_total_store_cnt,food_store_cnt,food_store_total_cnt,retail_lq
6,20212,송파구 위례동,편의점,0.0,100.0,-1.00,1,20,21,1.884032e+08,...,7.201550e+07,21.0,0.0,1.0,소매업,569022,712.0,91.0,100119,0.726397
12,20213,송파구 위례동,청과상,0.0,22.0,-0.22,9,0,9,2.533987e+08,...,1.476357e+08,9.0,0.0,2.0,소매업,578377,724.0,91.0,100324,0.724618
14,20213,송파구 위례동,의약품,0.0,0.0,0.00,11,1,12,1.044678e+08,...,5.226744e+07,12.0,0.0,0.0,소매업,578377,724.0,91.0,100324,0.724618
18,20214,송파구 위례동,청과상,0.0,0.0,0.00,9,0,9,3.079174e+08,...,1.734847e+08,9.0,0.0,0.0,소매업,595141,805.0,99.0,101177,0.723398
19,20214,송파구 위례동,의약품,0.0,0.0,0.00,11,1,12,1.627229e+08,...,8.307962e+07,12.0,0.0,0.0,소매업,595141,805.0,99.0,101177,0.723398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497316,20242,송파구 가락1동,미곡판매,0.0,0.0,0.00,11,0,11,2.370905e+10,...,1.129420e+10,11.0,0.0,0.0,소매업,575909,3295.0,2495.0,98528,4.425979
497317,20242,송파구 가락1동,육류판매,0.0,0.0,0.00,110,0,110,8.476766e+10,...,3.215757e+10,110.0,0.0,0.0,소매업,575909,3295.0,2495.0,98528,4.425979
497318,20242,송파구 가락1동,의약품,0.0,0.0,0.00,17,0,17,3.141933e+08,...,1.116833e+08,17.0,0.0,0.0,소매업,575909,3295.0,2495.0,98528,4.425979
497330,20234,송파구 가락1동,미곡판매,0.0,0.0,0.00,11,0,11,2.068183e+10,...,1.162871e+10,11.0,0.0,0.0,소매업,584072,3346.0,2523.0,99579,4.422725
497331,20234,송파구 가락1동,의약품,0.0,6.0,-0.06,17,0,17,3.045047e+08,...,1.193823e+08,17.0,0.0,1.0,소매업,584072,3346.0,2523.0,99579,4.422725

In [14]:
# 프랜차이즈 비율 LQ 지수 계산 (모든 데이터 사용)

df_gentrification['seoul_total_frc_cnt'] = df_gentrification.groupby(['quarter'])['franchise_count'].transform('sum')
df_gentrification['dong_total_frc_cnt'] = df_gentrification.groupby(['quarter', 'dong'])['franchise_count'].transform('sum')
df_gentrification['franchise_lq'] = (df_gentrification['dong_total_frc_cnt'] / df_gentrification['dong_total_store_cnt']) / (
    df_gentrification['seoul_total_frc_cnt'] / df_gentrification['seoul_total_store_cnt'])

df_gentrification['franchise_lq']

0         2.219522
1         2.219522
2         2.219522
3         2.158903
4         2.158903
            ...
497328    0.217122
497329    0.217122
497330    0.217122
497331    0.217122
497332    0.217122
Name: franchise_lq, Length: 497333, dtype: float64

In [15]:
# 청년층 매출액 비율 LQ 지수 계산 (모든 데이터 사용)
df_gentrification['youth_sales_amount'] = (
    df_gentrification['age_10s_sales_amount'] +
    df_gentrification['age_20s_sales_amount'] +
    df_gentrification['age_30s_sales_amount']
)
df_gentrification['seoul_total_sales'] = df_gentrification.groupby(['quarter'])['current_month_sales_amount'].transform('sum')
df_gentrification['dong_total_sales'] = df_gentrification.groupby(['quarter', 'dong'])['current_month_sales_amount'].transform('sum')
df_gentrification['seoul_total_youth_sales'] = df_gentrification.groupby(['quarter'])['youth_sales_amount'].transform('sum')
df_gentrification['dong_total_youth_sales'] = df_gentrification.groupby(['quarter', 'dong'])['youth_sales_amount'].transform('sum')
df_gentrification['youth_sales_lq'] = (df_gentrification['dong_total_youth_sales'] / df_gentrification['dong_total_sales']) / (
    df_gentrification['seoul_total_youth_sales'] / df_gentrification['seoul_total_sales'])

df_gentrification['youth_sales_lq']

0         1.386906
1         1.386906
2         1.386906
3         1.543515
4         1.543515
            ...
497328    0.711669
497329    0.711669
497330    0.711669
497331    0.711669
497332    0.711669
Name: youth_sales_lq, Length: 497333, dtype: float64

In [17]:
grouped = df_gentrification.groupby(['dong', 'quarter'], as_index=False).agg({
    'open_store_count': 'sum',
    'closed_store_count': 'sum',
    'store_total_count': 'first'
})

grouped['total_net_growth_rate'] = (
    ((grouped['open_store_count'] / grouped['store_total_count']) -
     (grouped['closed_store_count'] / grouped['store_total_count'])) * 100
)

df_gentrification = df_gentrification.merge(
    grouped[['dong', 'quarter', 'total_net_growth_rate']],
    on=['dong', 'quarter'],
    how='left'
)

In [20]:
print(df_gentrification.columns)

Index(['quarter', 'dong', 'service', 'opening_rate', 'closure_rate',
       'store_net_growth_rate', 'store_count', 'franchise_count',
       'store_total_count', 'current_month_sales_amount', 'sales_per_store',
       'age_10s_sales_amount', 'age_20s_sales_amount', 'age_30s_sales_amount',
       'age_40s_sales_amount', 'age_50s_sales_amount',
       'age_60_and_above_sales_amount', 'male_sales_amount',
       'female_sales_amount', 'similar_business_count', 'open_store_count',
       'closed_store_count', 'major', 'seoul_total_store_cnt',
       'dong_total_store_cnt', 'seoul_total_frc_cnt', 'dong_total_frc_cnt',
       'franchise_lq', 'youth_sales_amount', 'seoul_total_sales',
       'dong_total_sales', 'seoul_total_youth_sales', 'dong_total_youth_sales',
       'youth_sales_lq', 'total_net_growth_rate_x', 'total_net_growth_rate_y'],
      dtype='object')

In [21]:
print(df_gentrification[['total_net_growth_rate_x', 'total_net_growth_rate_y']].drop_duplicates())

        total_net_growth_rate_x  total_net_growth_rate_y
0                    540.000000               540.000000
3                    310.000000               310.000000
8                    150.000000               150.000000
15                   810.000000               810.000000
20                    23.076923                23.076923
...                         ...                      ...
166176              5500.000000              5500.000000
186968               800.000000               800.000000
207496                      NaN                      NaN
237579              2500.000000              2500.000000
264928              2300.000000              2300.000000

[2414 rows x 2 columns]

In [22]:
df_gentrification = df_gentrification.drop(columns=['total_net_growth_rate_x'])
df_gentrification.rename(columns={'total_net_growth_rate_y': 'total_net_growth_rate'}, inplace=True)

In [23]:
# 필요한 열 병합하여 lq 지수 테이블 산출
food_service_lq_df = food_service_df[['dong', 'quarter', 'food_service_lq']].drop_duplicates()

retail_lq_df = retail_df[['dong', 'quarter', 'retail_lq']].drop_duplicates()

franchise_lq_df = df_gentrification[['dong', 'quarter', 'franchise_lq']].drop_duplicates()

youth_sales_lq_df = df_gentrification[['dong', 'quarter', 'youth_sales_lq']].drop_duplicates()

net_growth_rate_df = df_gentrification[['dong', 'quarter', 'total_net_growth_rate']].drop_duplicates()

final_lq_df = food_service_lq_df.merge(
    retail_lq_df, on=['dong', 'quarter'], how='outer'
).merge(
    franchise_lq_df, on=['dong', 'quarter'], how='outer'
).merge(
    youth_sales_lq_df, on=['dong', 'quarter'], how='outer'
).merge(
    net_growth_rate_df, on=['dong', 'quarter'], how='outer'
)

In [24]:
final_lq_df

,dong,quarter,food_service_lq,retail_lq,franchise_lq,youth_sales_lq,total_net_growth_rate
0,송파구 위례동,20211,0.792873,0.749729,2.219522,1.386906,540.000000
1,송파구 위례동,20212,0.823023,0.726397,2.158903,1.543515,310.000000
2,송파구 위례동,20213,0.824284,0.724618,2.208791,1.575277,150.000000
3,송파구 위례동,20214,0.817079,0.723398,2.043944,1.525161,810.000000
4,송파구 위례동,20221,0.819005,0.716322,2.075974,1.434589,23.076923
...,...,...,...,...,...,...,...
5899,송파구 잠실7동,20233,0.311888,1.259296,0.875081,0.997117,20.000000
5900,강남구 개포1동,20234,0.336526,1.338416,0.609471,0.385341,-60.000000
5901,강남구 개포1동,20242,0.359586,1.363864,0.433076,1.014300,0.000000
5902,송파구 잠실7동,20241,0.295795,1.323843,0.847616,0.761001,-66.666667
5903,송파구 잠실7동,20242,0.297850,1.338042,0.860935,1.017511,-22.222222

In [25]:
final_lq_df.to_csv('final_lq_yes.csv', encoding = 'utf-8')